import { Task } from "@/types/task";

type DemoTask = Omit<Task, "status"> & {
  status: Task["status"] | "review" | "someday";
};

export const INITIAL_TASKS: DemoTask[] = [
  // --- Today Tasks (7) ---
  {
    id: "task-today-1",
    title: "Review project proposal",
    completed: false,
    status: "todo",
    view: "today",
    project: "work",
    projectEmoji: "🎯",
    projectName: "Work",
    section: "Sprint Q4",
    addedAgo: "10m ago",
    categoryIconType: "calendar",
    showFolderIcon: true,
    dueDate: "Today",
    dueBadge: "Today",
    dueBadgeVariant: "today",
    assigneeName: "Abram Vaccaro",
    tags: ["Review", "Work"],
    notes: "Review project proposal and verify timeline estimates with engineering team.",
    subtasks: [
      { id: "st-rev-1", title: "Review technical architecture", completed: false },
      { id: "st-rev-2", title: "Confirm budget estimates", completed: false },
    ],
    activity: [
      {
        id: "act-rev-1",
        time: "10:50 AM",
        actor: "Abram Vaccaro",
        description: 'created task in "Work".',
      },
    ],
  },
  {
    id: "task-today-2",
    title: "Complete client call notes",
    completed: true,
    status: "done",
    view: "today",
    project: "personal",
    projectEmoji: "😎",
    projectName: "Personal",
    section: "Daily",
    addedAgo: "1h ago",
    categoryIconType: "phone",
    showFolderIcon: false,
    dueDate: "Today",
    dueBadge: "Today",
    dueBadgeVariant: "today",
    assigneeName: "Abram Vaccaro",
    tags: ["Client", "Admin"],
    notes: "Call went well.\nKey takeaways: Add timeline for Q4 deliverables.\nSchedule follow-up for Tuesday.\nSend materials.",
    subtasks: [
      { id: "st-call-1", title: "Send follow-up email", completed: true },
    ],
    activity: [
      {
        id: "act-call-1",
        time: "11:05 AM",
        actor: "Abram Vaccaro",
        description: "marked as 'Done'",
      },
    ],
  },
  {
    id: "task-today-3",
    title: "Submit weekly expense report",
    completed: false,
    status: "todo",
    view: "today",
    project: "work",
    projectEmoji: "🎯",
    projectName: "Work",
    section: "Operations",
    addedAgo: "5h ago",
    categoryIconType: "doc",
    showFolderIcon: false,
    dueDate: "Today",
    dueBadge: "Today",
    dueBadgeVariant: "today",
    assigneeName: "Abram Vaccaro",
    tags: ["Finance", "Admin"],
    notes: "Gather receipts from travel and team meals, submit via corporate portal.",
    subtasks: [],
    activity: [
      {
        id: "act-exp-1",
        time: "07:00 AM",
        actor: "Abram Vaccaro",
        description: "created task.",
      },
    ],
  },
  {
    id: "task-today-4",
    title: "Finish design mockups",
    completed: false,
    status: "in_progress",
    view: "today",
    project: "work",
    projectEmoji: "🎯",
    projectName: "Work",
    section: "Design",
    addedAgo: "4h ago",
    categoryIconType: "palette",
    showFolderIcon: true,
    dueDate: "Today",
    dueBadge: "Today",
    dueBadgeVariant: "today",
    assigneeName: "Abram Vaccaro",
    tags: ["Design", "UI"],
    notes: "Finalize desktop and mobile layouts for client review.",
    subtasks: [],
    activity: [
      {
        id: "act-des-1",
        time: "08:15 AM",
        actor: "Abram Vaccaro",
        description: 'changed status to "In Progress".',
      },
    ],
  },
  {
    id: "task-today-5",
    title: "Plan team lunch",
    completed: false,
    status: "todo",
    view: "today",
    project: "work",
    projectEmoji: "🎯",
    projectName: "Work",
    section: "Team",
    addedAgo: "4h ago",
    categoryIconType: "utensil",
    showFolderIcon: true,
    dueDate: "Today",
    dueBadge: "Today",
    dueBadgeVariant: "today",
    assigneeName: "Abram Vaccaro",
    tags: ["Social", "Team"],
    notes: "Select venue with vegan and gluten-free options.",
    subtasks: [],
    activity: [],
  },
  {
    id: "task-today-6",
    title: "Daily Routine (Skincare)",
    completed: false,
    status: "todo",
    view: "today",
    project: "personal",
    projectEmoji: "😎",
    projectName: "Personal",
    section: "Skincare",
    addedAgo: "1h ago",
    categoryIconType: "calendar",
    showFolderIcon: true,
    dueDate: "Today",
    dueBadge: "Today",
    dueBadgeVariant: "today",
    assigneeName: "Abram Vaccaro",
    tags: ["Routine", "SelfCare"],
    notes: "My simple morning skincare steps.\nRemember to use sunscreen after moisturizing.\nCleanse, Tone\nMoisturize\nSunscreen.",
    subtasks: [
      { id: "sub-1", title: "Face Wash", completed: true },
      { id: "sub-2", title: "Apply Toner", completed: true },
      { id: "sub-3", title: "Apply Moisturizer", completed: false },
      { id: "sub-4", title: "Apply Sunscreen", completed: false },
    ],
    activity: [
      {
        id: "act-1",
        time: "11:00 AM",
        actor: "Abram Vaccaro",
        description: 'updated status to "To Do".',
      },
    ],
  },
  {
    id: "task-today-7",
    title: "Walk the dog",
    completed: false,
    status: "todo",
    view: "today",
    project: "personal",
    projectEmoji: "😎",
    projectName: "Personal",
    section: "Home & Family",
    addedAgo: "1h ago",
    categoryIconType: "dog",
    showFolderIcon: true,
    dueDate: "Today",
    dueBadge: "Today",
    dueBadgeVariant: "today",
    assigneeName: "Abram Vaccaro",
    tags: ["Personal", "Pets"],
    notes: "30-minute evening walk in the neighborhood park.",
    subtasks: [],
    activity: [],
  },

  // --- Personal Project View Additional Tasks ---
  {
    id: "task-personal-2",
    title: "Deep Exfoliation",
    completed: false,
    status: "todo",
    view: "upcoming",
    project: "personal",
    projectEmoji: "😎",
    projectName: "Personal",
    section: "Skincare",
    dueDate: "Tomorrow",
    dueBadge: "Tomorrow",
    dueBadgeVariant: "tomorrow",
    assigneeName: "Abram Vaccaro",
    tags: ["Routine", "Skincare"],
    notes: "Use AHA/BHA gentle exfoliating serum.",
    subtasks: [],
    activity: [],
  },
  {
    id: "task-personal-3",
    title: "5km Run",
    completed: false,
    status: "todo",
    view: "upcoming",
    project: "personal",
    projectEmoji: "😎",
    projectName: "Personal",
    section: "Fitness",
    dueDate: "This weekend",
    dueBadge: "This weekend",
    dueBadgeVariant: "tomorrow",
    assigneeName: "Abram Vaccaro",
    tags: ["Fitness", "Cardio"],
    notes: "Target pace: 5:30/km.",
    subtasks: [],
    activity: [],
  },
  {
    id: "task-personal-4",
    title: "Gym Session - Upper Body",
    completed: false,
    status: "in_progress",
    view: "today",
    project: "personal",
    projectEmoji: "😎",
    projectName: "Personal",
    section: "Fitness",
    dueDate: "Today",
    dueBadge: "Today",
    dueBadgeVariant: "today",
    assigneeName: "Abram Vaccaro",
    tags: ["Fitness", "Gym"],
    notes: "Bench press, Incline dumbbell press, Pull-ups.",
    subtasks: [],
    activity: [],
  },
  {
    id: "task-personal-5",
    title: "Yoga Session",
    completed: false,
    status: "todo",
    view: "today",
    project: "personal",
    projectEmoji: "😎",
    projectName: "Personal",
    section: "Fitness",
    dueDate: "2 days ago",
    dueBadge: "Overdue (2 days)",
    dueBadgeVariant: "overdue",
    assigneeName: "Abram Vaccaro",
    tags: ["Fitness", "Mobility"],
    notes: "20 min full body recovery flow.",
    subtasks: [],
    activity: [],
  },

  // --- Upcoming Tasks (3) ---
  {
    id: "task-upcoming-1",
    title: "Finish client pitch deck",
    completed: true,
    status: "done",
    view: "upcoming",
    project: "work",
    projectEmoji: "🎯",
    projectName: "Work",
    section: "Sprint Q4",
    dueDate: "This week",
    dueBadge: "This week",
    dueBadgeVariant: "upcoming",
    addedAgo: "1 day ago",
    categoryIconType: "calendar",
    showFolderIcon: true,
    assigneeName: "Abram Vaccaro",
    tags: ["Pitch", "Client"],
    notes: "Final deck ready for client presentation.",
    subtasks: [],
    activity: [
      {
        id: "act-pitch-1",
        time: "09:30 AM",
        actor: "Abram Vaccaro",
        description: "marked as 'Done'",
      },
    ],
  },
  {
    id: "task-upcoming-2",
    title: "Prepare final Q4 deliverables",
    completed: false,
    status: "todo",
    view: "upcoming",
    project: "work",
    projectEmoji: "🎯",
    projectName: "Work",
    section: "Sprint Q4",
    dueDate: "Next week",
    dueBadge: "Next week",
    dueBadgeVariant: "upcoming",
    addedAgo: "2 days ago",
    categoryIconType: "calendar",
    showFolderIcon: true,
    assigneeName: "Abram Vaccaro",
    tags: ["Q4", "Strategic", "Milestone"],
    notes: "Need to consolidate input from all departments. Must include resource allocation plan and performance metrics for next year.\nPreliminary draft is due before the final review.",
    subtasks: [
      { id: "sub-q4-1", title: "Collect department reports", completed: false },
      { id: "sub-q4-2", title: "Schedule final review with Sarah", completed: false },
    ],
    activity: [
      {
        id: "act-q4-1",
        time: "12:15 PM",
        actor: "Abram Vaccaro",
        description: "updated notes.",
      },
    ],
  },
  {
    id: "task-upcoming-3",
    title: "Annual strategic planning meeting",
    completed: false,
    status: "todo",
    view: "upcoming",
    project: "work",
    projectEmoji: "🎯",
    projectName: "Work",
    section: "Executive",
    dueDate: "In two weeks",
    dueBadge: "In two weeks",
    dueBadgeVariant: "upcoming",
    addedAgo: "3 days ago",
    categoryIconType: "book",
    showFolderIcon: true,
    assigneeName: "Abram Vaccaro",
    tags: ["Strategy", "Annual"],
    notes: "Prepare slides for department heads.",
    subtasks: [],
    activity: [],
  },

  // --- Someday Tasks (5) ---
  {
    id: "task-someday-1",
    title: "Design custom phone icons",
    completed: false,
    status: "someday",
    view: "someday",
    category: "Ideas & Inspiration 💡",
    project: "personal",
    projectEmoji: "😎",
    projectName: "Personal",
    addedAgo: "1 day ago",
    showFolderIcon: true,
    dueDate: "No Due Date",
    assigneeName: "Abram Vaccaro",
    tags: ["Design", "Icons"],
    notes: "Vector set for iOS home screen.",
    subtasks: [],
    activity: [],
  },
  {
    id: "task-someday-2",
    title: "Plan a photography workshop",
    completed: false,
    status: "someday",
    view: "someday",
    category: "Ideas & Inspiration 💡",
    project: "personal",
    projectEmoji: "😎",
    projectName: "Personal",
    addedAgo: "1 day ago",
    showFolderIcon: true,
    dueDate: "No Due Date",
    assigneeName: "Abram Vaccaro",
    tags: ["Photo", "Workshop"],
    notes: "Weekend landscape photography basics.",
    subtasks: [],
    activity: [],
  },
  {
    id: "task-someday-3",
    title: "Master advanced spreadsheet functions",
    completed: false,
    status: "someday",
    view: "someday",
    category: "Learning & Courses 📚",
    project: "work",
    projectEmoji: "🎯",
    projectName: "Work",
    addedAgo: "1 day ago",
    showFolderIcon: true,
    dueDate: "No Due Date",
    assigneeName: "Abram Vaccaro",
    tags: ["Excel", "Skills"],
    notes: "Learn XLOOKUP, INDEX/MATCH, and dynamic arrays.",
    subtasks: [],
    activity: [],
  },
  {
    id: "task-someday-4",
    title: "Build a portfolio website",
    completed: false,
    status: "someday",
    view: "someday",
    category: "Creative Projects 🎨",
    project: "personal",
    projectEmoji: "🎨",
    projectName: "Personal",
    addedAgo: "1 day ago",
    showFolderIcon: true,
    dueDate: "No Due Date",
    assigneeName: "Abram Vaccaro",
    tags: [],
    notes: "Need to research modern layout styles.\nPlan structure and content.\nMaybe use Notion or Webflow.\nNotion or Webflow.\nFocus on highlighting case studies.",
    subtasks: [
      { id: "sub-port-1", title: "Wireframe homepage", completed: false },
      { id: "sub-port-2", title: "Draft project descriptions", completed: false },
    ],
    activity: [
      {
        id: "act-port-1",
        time: "12:30 PM",
        actor: "Abram Vaccaro",
        description: "added notes.",
      },
    ],
  },
  {
    id: "task-someday-5",
    title: "Start writing a novel",
    completed: false,
    status: "someday",
    view: "someday",
    category: "Creative Projects 🎨",
    project: "personal",
    projectEmoji: "😎",
    projectName: "Personal",
    addedAgo: "1 day ago",
    showFolderIcon: true,
    dueDate: "No Due Date",
    assigneeName: "Abram Vaccaro",
    tags: ["Writing"],
    notes: "Draft chapter 1 outline and character arcs.",
    subtasks: [],
    activity: [],
  },
];
